# Project information

site_name: r00tz CTF on AWS
site_short_name: r00tz CTF on AWS
site_description: 'This workshop is for kids ages 8 - 18 to become more familiar with cloud security concepts.'
site_author: 'aws-security-workshops@amazon.com'
site_url: 'https://r00tz-ctf.awssecworkshops.com/'

# Repository
repo_name: 'aws-samples/r00tz-ctf-on-aws'
repo_url: 'https://github.com/aws-samples/r00tz-ctf-on-aws'

# Copyright
copyright: '<a href="https://aws.amazon.com/privacy/" target="_blank">Privacy</a> | <a href="https://aws.amazon.com/terms/" target="_blank">Site terms</a> | &copy; 2020, Amazon Web Services, Inc. or its affiliates. All rights reserved.'

# Configuration
theme:
  name: 'material'
  logo: 'assets/images/aws_smile_logo.png'
  favicon: 'assets/images/aws-favicon.ico'

# Customization
extra_css:
  - 'stylesheets/custom.css'
extra:
  social:
    - icon: fontawesome/solid/home
      link: https://awssecworkshops.com
    - icon: fontawesome/solid/shield-alt
      link: https://aws.amazon.com/security/
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/awssecurityinfo?lang=en
    - icon: fontawesome/solid/rss-square
      link: https://aws.amazon.com/blogs/security/

# Extensions
markdown_extensions:
  - admonition
  - codehilite
  - pymdownx.details

# Navigation
nav:
  - Security Capture the Flag (CTF): 'index.md'
  - Environment Setup: 'environment-setup.md'
  - Instructor Walkthrough: 'walkthrough.md'
  - Contributing: 'contribute.md'
  - License: 'license.md'